{
 "title": "ENTSOE-Monitor",
 "description": "Monitor of the open available Data from ENTSO-E FMS",
 "tags": [ "open-data" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "WITH price_areas AS (\n    SELECT DISTINCT \"AreaDisplayName\" AS area_name\n    FROM entsoe_fms.\"EnergyPrices\"\n    WHERE \"DateTime(UTC)\" >= now() - interval '730 days'\n      AND \"AreaTypeCode\" = 'BZN'\n),\nload_areas AS (\n    SELECT DISTINCT \"AreaDisplayName\" AS area_name\n    FROM entsoe_fms.\"ActualTotalLoad\"\n    WHERE \"DateTime(UTC)\" >= now() - interval '730 days'\n)\nSELECT p.area_name\nFROM price_areas p\nJOIN load_areas l ON l.area_name = p.area_name\nORDER BY 1"
   }
  ]
 },
 "panels": [
  { "title": "Europa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Actual Power Europe (sum over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  sum(\"TotalLoad[MW]\"/($__interval_ms/1000/3600)) AS \"actual_load\"\nFROM entsoe_fms.\"ActualTotalLoad\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\") AND\n  \"TotalLoad[MW]\" IS NOT NULL AND\n  \"AreaDisplayName\" IN ('DE-LU','Austria (AT)','France (FR)','Poland (PL)','Italy (IT)','Spain (ES)','Portugal (PT)','Switzerland (CH)','Belgium (BE)','Netherlands (NL)','GB','United Kingdom (UK)','Sweden (SE)','Norway (NO)')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  sum(\"TotalLoad[MW]\"/($__interval_ms/1000/3600)) AS \"forecasted_load\"\nFROM entsoe_fms.\"DayAheadTotalLoadForecast\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\") AND\n  \"TotalLoad[MW]\" IS NOT NULL AND\n  \"AreaDisplayName\" IN ('DE-LU','Austria (AT)','France (FR)','Poland (PL)','Italy (IT)','Spain (ES)','Portugal (PT)','Switzerland (CH)','Belgium (BE)','Netherlands (NL)','GB','United Kingdom (UK)','Sweden (SE)','Norway (NO)')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  sum(\"ActualGenerationOutput[MW]\"/($__interval_ms/1000/3600)) AS \"generation_sum\"\nFROM entsoe_fms.\"AggregatedGenerationPerType\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\") AND\n  \"ActualGenerationOutput[MW]\" IS NOT NULL\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  sum(\"GenerationForecast[MW]\") AS \"forecasted_generation\",\n  sum(\"ScheduledConsumption[MW]\") AS \"forecasted_consumption\"\nFROM entsoe_fms.\"DayAheadAggregatedGeneration\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ENTSOE-Power systems",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  lat,\n  lon,\n  capacity,\n  country,\n  fuel_type AS energy_source\nFROM power_system_data.powersystemdata\nWHERE lat IS NOT NULL\n  AND lon IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ENTSOE Day-Ahead-Prices (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  \"AreaDisplayName\" AS metric,\n  avg(\"Price[Currency/MWh]\") AS \"\"\"0\"\"\"\nFROM entsoe_fms.\"EnergyPrices\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\") AND\n  \"Price[Currency/MWh]\" IS NOT NULL AND\n  \"AreaTypeCode\" = 'BZN' AND\n  (trim(coalesce(\"Sequence\", '')) = '' OR \"Sequence\" = '1')\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "ENTSO-E", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Load $country (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  avg(\"TotalLoad[MW]\") AS \"actual_load\"\nFROM entsoe_fms.\"ActualTotalLoad\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\") AND\n  \"AreaDisplayName\" = '$country'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  avg(\"TotalLoad[MW]\") AS \"forecasted_load\"\nFROM entsoe_fms.\"DayAheadTotalLoadForecast\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\") AND\n  \"AreaDisplayName\" = '$country'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Erzeugungsleistung $country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  make_timestamp(\"Year\"::int, 1, 1, 0, 0, 0) AS \"time\",\n  sum(CASE WHEN \"ProductionType\" = 'Biomass' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS biomass,\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Hard coal' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS fossil_hard_coal,\n    sum(CASE WHEN \"ProductionType\" = 'Geothermal' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS geothermal,\n    sum(CASE WHEN \"ProductionType\" = 'Nuclear' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS nuclear,\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Brown coal/Lignite' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS \"fossil_brown_coal/lignite\",\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Coal-derived gas' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS \"fossil_coal-derived_gas\",\n    sum(CASE WHEN \"ProductionType\" = 'Hydro Run-of-river and poundage' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS \"hydro_run-of-river_and_poundage\",\n    sum(CASE WHEN \"ProductionType\" = 'Waste' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS waste,\n    sum(CASE WHEN \"ProductionType\" = 'Hydro Pumped Storage' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS hydro_pumped_storage,\n    sum(CASE WHEN \"ProductionType\" = 'Solar' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS solar,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Offshore' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_offshore,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Onshore' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_onshore,\n    sum(CASE WHEN \"ProductionType\" = 'Other renewable' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS other_renewable,\n    sum(CASE WHEN \"ProductionType\" = 'Hydro Water Reservoir' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS hydro_water_reservoir,\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Gas' THEN coalesce(\"AggregatedInstalledCapacity[MW]\"::double precision, 0.0) ELSE 0.0 END) AS fossil_gas\nFROM entsoe_fms.\"InstalledGenerationCapacityAggregated\"\nWHERE\n  $__timeFilter(make_timestamp(\"Year\"::int, 1, 1, 0, 0, 0)) AND\n  \"AreaDisplayName\" = '$country'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stromerzeugung $country (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "WITH generation AS (\n  SELECT\n    \"DateTime(UTC)\" AS ts,\n    sum(CASE WHEN \"ProductionType\" = 'Biomass' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS biomass,\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Hard coal' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS fossil_hard_coal,\n    sum(CASE WHEN \"ProductionType\" = 'Geothermal' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS geothermal,\n    sum(CASE WHEN \"ProductionType\" = 'Nuclear' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS nuclear,\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Brown coal/Lignite' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS \"fossil_brown_coal/lignite\",\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Coal-derived gas' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS \"fossil_coal-derived_gas\",\n    sum(CASE WHEN \"ProductionType\" = 'Hydro Run-of-river and poundage' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS \"hydro_run-of-river_and_poundage\",\n    sum(CASE WHEN \"ProductionType\" = 'Waste' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS waste,\n    sum(CASE WHEN \"ProductionType\" = 'Hydro Pumped Storage' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS hydro_pumped_storage,\n    sum(CASE WHEN \"ProductionType\" = 'Solar' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS solar,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Offshore' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_offshore,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Onshore' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_onshore,\n    sum(CASE WHEN \"ProductionType\" = 'Other renewable' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS other_renewable,\n    sum(CASE WHEN \"ProductionType\" = 'Hydro Water Reservoir' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS hydro_water_reservoir,\n    sum(CASE WHEN \"ProductionType\" = 'Fossil Gas' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS fossil_gas\n  FROM entsoe_fms.\"AggregatedGenerationPerType\"\n  WHERE\n    $__timeFilter(\"DateTime(UTC)\") AND\n    \"AreaDisplayName\" = '$country'\n  GROUP BY 1\n)\nSELECT\n  $__timeGroupAlias(ts,$__interval),\n  avg(biomass) as biomass,\n  avg(fossil_hard_coal) as fossil_hard_coal,\n  avg(geothermal) as geothermal,\n  avg(nuclear) as nuclear,\n  avg(\"fossil_brown_coal/lignite\") as \"fossil_brown_coal/lignite\",\n  avg(\"fossil_coal-derived_gas\") as \"fossil_coal-derived_gas\",\n  avg(\"hydro_run-of-river_and_poundage\") as \"hydro_run-of-river_and_poundage\",\n  avg(waste) as waste,\n  avg(solar) as solar,\n  avg(wind_offshore) as wind_offshore,\n  avg(wind_onshore) as wind_onshore,\n  avg(other_renewable) as other_renewable,\n  avg(hydro_water_reservoir) as hydro_water_reservoir,\n  avg(fossil_gas) as fossil_gas\nFROM generation\ngroup by 1\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "ENTSOE Day-Ahead-Prices (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"DateTime(UTC)\",$__interval),\n  avg(\"Price[Currency/MWh]\") AS \"da_price\"\nFROM entsoe_fms.\"EnergyPrices\"\nWHERE\n  $__timeFilter(\"DateTime(UTC)\") AND\n  \"AreaDisplayName\" = '$country' AND\n  \"AreaTypeCode\" = 'BZN' AND\n  (trim(coalesce(\"Sequence\", '')) = '' OR \"Sequence\" = '1')\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Compare RES forecast - with actual (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "WITH forecast AS (\n  SELECT\n    \"DateTime(UTC)\" AS ts,\n    sum(CASE WHEN \"ProductionType\" = 'Solar' THEN coalesce(\"DayAheadGenerationForecast[MW]\"::double precision, 0.0) ELSE 0.0 END) AS solar,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Onshore' THEN coalesce(\"DayAheadGenerationForecast[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_onshore,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Offshore' THEN coalesce(\"DayAheadGenerationForecast[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_offshore\n  FROM entsoe_fms.\"GenerationForecastsForWindAndSolar\"\n  WHERE $__timeFilter(\"DateTime(UTC)\")\n  GROUP BY 1\n)\nSELECT\n  $__timeGroupAlias(ts,$__interval),\n  sum(solar/($__interval_ms/1000/3600)) AS \"solar_fc\",\n  sum(wind_onshore/($__interval_ms/1000/3600)) AS \"wind_onshore_fc\",\n  sum(wind_offshore/($__interval_ms/1000/3600)) AS \"wind_offshore_fc\"\nFROM forecast\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "WITH generation AS (\n  SELECT\n    \"DateTime(UTC)\" AS ts,\n    sum(CASE WHEN \"ProductionType\" = 'Solar' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS solar,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Onshore' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_onshore,\n    sum(CASE WHEN \"ProductionType\" = 'Wind Offshore' THEN coalesce(\"ActualGenerationOutput[MW]\"::double precision, 0.0) ELSE 0.0 END) AS wind_offshore\n  FROM entsoe_fms.\"AggregatedGenerationPerType\"\n  WHERE $__timeFilter(\"DateTime(UTC)\")\n  GROUP BY 1\n)\nSELECT\n  $__timeGroupAlias(ts,$__interval),\n  sum(solar/($__interval_ms/1000/3600)) AS \"solar\",\n  sum(wind_onshore/($__interval_ms/1000/3600)) AS \"wind_onshore\",\n  sum(wind_offshore/($__interval_ms/1000/3600)) AS \"wind_offshore\"\nFROM generation\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}